# Generated by Django 2.2.7 on 2020-06-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200625_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registration',
            name='job',
            field=models.CharField(max_length=50),
        ),
    ]
